---
title: "Economía Mexicana"
format:
  dashboard:
    logo: images/lytica_logo_white_bk.png
    orientation: columns
editor: visual
---

# Histórico

## Column {width="35%"}

```{r}
#| label: librerias
#| warning: false
#| message: false

# librerias
library(tidyverse)
library(styleBreton)
```

```{r}
#| label: carga de datos
#| warning: false
#| message: false
#| echo: false
#| include: false

# importa datos
suppressMessages(source("source/data_clean_b18_00.R"))
```

```{r}
#| label: implementacion de secuencia

## preparación de secuencia
secuen <- function(base){
  seq_along(along.with = base$valor)
}

# implementación de secuencia
df02 <- 
  df01 |> 
  mutate(id_mes = str_c(mes, 
                        str_extract(year(fecha_final), "\\d{2}$"), 
                        sep = "_")) |> 
  nest(.by = concepto) |> 
  mutate(sec = map(data, secuen)) |> 
  unnest(cols = everything())
```

```{r}
#| label: último mes de la serie

# extracción de último mes de la serie
ulti_fecha <- 
  df02 |> 
  filter(concepto == "Indicador Global de la Actividad Económica" & 
           fecha_final == max(fecha_final)) |> 
  pull(fecha_final)
```

::: {.card title="Crecimiento Anual del IGAE"}
```{r}
#| label: variacion 12 meses global

## cálculo de tasas de cambio GLOBAL
año_anterior <- df01 %>% 
  filter(concepto == "Indicador Global de la Actividad Económica") %>% 
  filter(fecha == max(fecha) - years(1)) %>% 
  pull(valor)

año_actual <- df01 %>% 
  filter(concepto == "Indicador Global de la Actividad Económica") %>% 
  filter(fecha == max(fecha)) %>% 
  pull(valor)

# value box
bslib::value_box(
  paste("Variación respecto a", 
        format(ulti_fecha - years(1), "%B %Y")),
  theme = "primary",
  value = scales::percent((año_actual - año_anterior) / año_anterior,
                          accuracy = 0.01)
)
```
:::

::: {.card title="Crecimiento Mensual del IGAE"}
```{r}
#| label: variacion mes anterior global

# cambio a 1 mes
mes_anterior <- df01 %>% 
  filter(concepto == "Indicador Global de la Actividad Económica") %>% 
  filter(fecha == max(fecha) - months(1)) %>% 
  pull(valor)

mes_actual <- df01 %>% 
  filter(concepto == "Indicador Global de la Actividad Económica") %>% 
  filter(fecha == max(fecha)) %>% 
  pull(valor)

# value box
bslib::value_box(
  paste("Variación respecto a", 
        format(ulti_fecha - month(1), "%B %Y")),
  theme = "primary",
  value = scales::percent((mes_actual - mes_anterior) / mes_anterior,
                          accuracy = 0.01)
)
```
:::

## Column {width="65%"}

::: {.card title="Desempeño Histórico del Indicador Global de la Actividad Económica"}
```{r}
#| label: visualización de las 4 series
#| warning: false
#| message: false


# texto para caption
text_cap <-  
  paste0("hasta ", 
        format(ulti_fecha, "%b %Y"),
        ".")

# visualización de 4 series
df02 |> 
  ggplot() +
  geom_line(data = df02 |> 
              filter(concepto == "Actividades primarias"),
            aes(x = fecha_final, 
                y = valor, 
                group = concepto,
                color = "Act. Primarias"),
            alpha = 0.35) +
  geom_line(data = df02 |> 
              filter(concepto == "Actividades secundarias"),
            aes(x = fecha_final, 
                y = valor, 
                group = concepto,
                color = "Act. Secundarias"),
            alpha = 0.35) +
  geom_line(data = df02 |> 
              filter(concepto == "Actividades terciarias"),
            aes(x = fecha_final, 
                y = valor, 
                group = concepto,
                color = "Act. Terciarias"),
            alpha = 0.35) +
  geom_line(data = df02 |> 
              filter(concepto == "Indicador Global de la Actividad Económica"),
            aes(x = fecha_final, 
                y = valor, 
                group = concepto,
                color = "Global"),
            alpha = 0.85,
            linewidth = 0.85) +
  scale_color_manual(name = "Indicador",
                     breaks = c("Global", "Act. Primarias",
                                "Act. Secundarias", "Act. Terciarias"),
                     values = c("#B22203", "#06B304", 
                                "#00238D", "#9003C2")) +
  labs(title = "Desemepeño Histórico de las Series del IGAE",
       subtitle = paste("Indicadores de actividad económica Global, Primaria, Secundaria y Terciaria", text_cap),
       y = "Índice a valores constantes (base 2018)",
       x = "Mes",
       caption = paste("Fuente: INEGI: 
         Indicador Global de la Actividad Económica, base 2018, 
         series desestacionalizadas.<br>
         Modeladoe y visualización: Juan L. Bretón, PMP | @juanlbreton")) +
  theme_breton() +
  theme(legend.position = "top",
        axis.text.x = element_text(size = rel(0.85)),
        panel.grid.major = element_line(color = "grey97"),
        panel.grid.minor = element_blank()) +
  scale_x_date(breaks = seq(min(df02$fecha_final),
                            max(df02$fecha_final),
                            length.out = 10),
               date_labels = "%Y_%m")
```
:::

# Comparado
